### ISSUE TITLE
Allow configuring clickhouse-driver `server_side_params`

### ISSUE THREAD

**Issue by PHameete** [bryzgaloff/airflow-clickhouse-plugin#86] opened 2024-06-06 20:46 UTC
After upgrading the `clickhouse-airflow-plugin` to 1.3.0 the `clickhouse-driver` got updated to 0.2.7 as well.

That version of the `clickhouse-driver` includes a commit that disables Server Side Parameter Substitution by default, breaking all DAGs that make use of this functionality. See https://github.com/mymarilyn/clickhouse-driver/commit/24e8b3592e29948294d3b7feaae6734154a225cc#diff-ea3e168b7a6e0e795b66587636dd954c124334f970be899db78a3b949fbfead5

Could you add a parameter to the ClickHouse operator that allows either to pass in arbitrary settings to the underlying `clickhouse-driver` Client, or to specifically allow overriding the setting for `server_side_params`?

I am willing to prepare a PR for this as well if you prefer. Thanks in advance!

**Comment by bryzgaloff** [comment] 2024-06-18 09:15
Hi @PHameete and thank you for a detailed report. Would freezing a version of clickhouse-driver during pip install solve your issue? The plugin's dependency is defined as follows:

https://github.com/bryzgaloff/airflow-clickhouse-plugin/blob/1e3fb482227212a66c4ab6bfd7dc82188449f64e/requirements.txt#L1

Which means that you may `pip install airflow-clickhouse-plugin clickhouse-driver<0.2.7` to install the combination of versions you require.

Regarding any additional logic in the plugin, my approach aims to keep it lightweight and minimize custom behaviour features, fully relying on the underlying dependencies. Unless there's a fundamental issue with the underlying dependency affecting the plugin broadly (and not just in isolated cases), we prefer not to make changes. It keeps the plugin very flexible and its behaviour predictable.

Could you please confirm if this solution works for your needs? Once confirmed, we can proceed to close the issue.

**Comment by bryzgaloff** [comment] 2024-06-23 08:07
I am closing the issue since I have not received any reply from you. Anyway, feel free to post an update here :)

**Closed by bryzgaloff** 2024-06-23 08:07 UTC

**Comment by PHameete** [comment] 2024-06-25 13:12
Hey @bryzgaloff - apologies for the late reply I was on holidays.

Fixing the clickhouse-driver version works. But that also means we can't get any future upgrades. In the long run I don't think that will work (i.e. due to API changes, or security patches). 

In this case the clickhouse-driver changed a default, and there is no way to change that param other than through the `airflow-clickhouse-plugin`. Not being able to change that default means we can't use the `airflow-clickhouse-plugin` when using server side param substituion in our queries. 

I think this is not an isolated case, it affects everyone that uses server side param substitution.

**Comment by bryzgaloff** [comment] 2024-06-26 10:06
Hi @PHameete currently the plugin passes all the arguments to the driver's `Client` as-is:

https://github.com/bryzgaloff/airflow-clickhouse-plugin/blob/1e3fb482227212a66c4ab6bfd7dc82188449f64e/src/airflow_clickhouse_plugin/hooks/clickhouse.py#L54

Which means that you can set `server_side_params=True` through Airflow connection's `extra`: https://airflow.apache.org/docs/apache-airflow/stable/howto/connection.html#custom-connection-fields

As you may see in `conn_to_kwargs` function, it preserves all the `extra` parameters (and also `dejson`s them, so `extra={"server_side_params":true}` should work for you):

https://github.com/bryzgaloff/airflow-clickhouse-plugin/blob/1e3fb482227212a66c4ab6bfd7dc82188449f64e/src/airflow_clickhouse_plugin/hooks/clickhouse.py#L93C5-L108

Please let me know if it addresses your concern or am I missing something. I am open to adapting the plugin but the priority is to keep it as lightweight as possible and introduce no behaviour overrides.
